import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from './Components/ThemeProvider'
import Header from "./Components/Header";
import Footer from './Components/Footer'
import { Josefin_Slab, Berkshire_Swash } from 'next/font/google'

const josefinSlab = Josefin_Slab({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-josefin-slab',
})

const berkshireSwash = Berkshire_Swash({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-berkshire-swash',
})

export const metadata: Metadata = {
  title: "Rupa's Serf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${josefinSlab.variable} ${berkshireSwash.variable}`}>
      <body className={` min-h-screen`}>
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
